"""
Skrybix Web — minimal working prototype

This is a proof-of-concept replacement for the Google Sheets + Apps Script
version of Skrybix. It reproduces the same core workflow:

  Mother Plants  --(take cuttings)-->  Cuttings  --(sold)-->  Outgoing Log
                                          |
                                          +--> printable labels (CSV + PDF, with real QR codes)

What this fixes vs. the Sheets version, by construction:
  - CSV export uses Python's csv module, so commas/quotes in plant names
    can never corrupt the file (the original Apps Script did naive
    string.join(',') with no escaping).
  - Every cutting gets its own correctly-derived QR code, generated at
    export time from its own Cutting_ID/Mother_ID (the Sheets version
    copied one hardcoded QR value from row 2 onto every new cutting).
  - IDs are generated by a single get_or_create sequence per mother with
    no fixed-width truncation, so id numbering doesn't wrap past 99.
  - All writes go through a real SQLite database with transactions,
    instead of direct cell writes that can race with onEdit/onFormSubmit
    triggers firing concurrently.
  - This is a *prototype*, not a production app: no auth, no multi-user
    permissions, no hosting config. See the review doc for what a real
    rollout would still need (auth, backups, a proper printer pipeline).

Run:
    pip install -r requirements.txt
    python app.py
Then open http://127.0.0.1:5000
"""
import csv
import io
import sqlite3
from datetime import datetime, date

from flask import Flask, request, redirect, url_for, render_template, g, send_file, flash, abort

import qrcode
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader

DB_PATH = "skrybix.db"

app = Flask(__name__)
app.secret_key = "skrybix-prototype-dev-key"  # fine for a local prototype only


# ----------------------------------------------------------------
# DB helpers
# ----------------------------------------------------------------
def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
        g.db.execute("PRAGMA foreign_keys = ON")
    return g.db


@app.teardown_appcontext
def close_db(exception=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = sqlite3.connect(DB_PATH)
    db.executescript(
        """
        CREATE TABLE IF NOT EXISTS mother_plants (
            mother_id       TEXT PRIMARY KEY,
            display_name    TEXT NOT NULL,
            location        TEXT,
            botanical_line1 TEXT,
            botanical_line2 TEXT,
            print_label     INTEGER NOT NULL DEFAULT 0,
            created_at      TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS cuttings (
            cutting_id        TEXT PRIMARY KEY,
            mother_id         TEXT NOT NULL REFERENCES mother_plants(mother_id),
            full_display_name TEXT,
            label_line1       TEXT,
            label_line2       TEXT,
            date_taken        TEXT,
            sold              INTEGER NOT NULL DEFAULT 0,
            print_label       INTEGER NOT NULL DEFAULT 0,
            created_at        TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS outgoing_log (
            id                 INTEGER PRIMARY KEY AUTOINCREMENT,
            date_out           TEXT NOT NULL,
            cutting_id         TEXT NOT NULL,
            full_display_name  TEXT,
            qty                INTEGER NOT NULL DEFAULT 1,
            reason             TEXT,
            selling_platform   TEXT,
            notes              TEXT
        );
        """
    )
    db.commit()
    db.close()


# ----------------------------------------------------------------
# Shared logic
# ----------------------------------------------------------------
def next_cutting_seq(db, mother_id):
    """Highest existing sequence number for this mother's cuttings, +1.
    Uses zero-padded width that grows past 99 instead of truncating
    (the bug in the original Apps Script: ('0'+seq).slice(-2))."""
    prefix = mother_id + "-C"
    rows = db.execute(
        "SELECT cutting_id FROM cuttings WHERE cutting_id LIKE ?", (prefix + "%",)
    ).fetchall()
    max_seq = 0
    for r in rows:
        tail = r["cutting_id"][len(prefix):]
        if tail.isdigit():
            max_seq = max(max_seq, int(tail))
    return max_seq + 1


def make_cutting_id(mother_id, seq):
    width = 2 if seq < 100 else len(str(seq))
    return f"{mother_id}-C{str(seq).zfill(width)}"


def qr_png_bytes(url_text):
    img = qrcode.make(url_text, box_size=6, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


# ----------------------------------------------------------------
# Dashboard
# ----------------------------------------------------------------
@app.route("/")
def dashboard():
    db = get_db()
    mother_count = db.execute("SELECT COUNT(*) c FROM mother_plants").fetchone()["c"]
    cutting_count = db.execute("SELECT COUNT(*) c FROM cuttings WHERE sold = 0").fetchone()["c"]
    sold_pending = db.execute("SELECT COUNT(*) c FROM cuttings WHERE sold = 1").fetchone()["c"]
    outgoing_count = db.execute("SELECT COUNT(*) c FROM outgoing_log").fetchone()["c"]
    print_mothers = db.execute("SELECT COUNT(*) c FROM mother_plants WHERE print_label = 1").fetchone()["c"]
    print_cuttings = db.execute("SELECT COUNT(*) c FROM cuttings WHERE print_label = 1").fetchone()["c"]
    recent_outgoing = db.execute(
        "SELECT * FROM outgoing_log ORDER BY id DESC LIMIT 8"
    ).fetchall()
    return render_template(
        "dashboard.html",
        mother_count=mother_count,
        cutting_count=cutting_count,
        sold_pending=sold_pending,
        outgoing_count=outgoing_count,
        print_mothers=print_mothers,
        print_cuttings=print_cuttings,
        recent_outgoing=recent_outgoing,
    )


# ----------------------------------------------------------------
# Mother plants
# ----------------------------------------------------------------
@app.route("/mothers")
def mothers_list():
    db = get_db()
    rows = db.execute("SELECT * FROM mother_plants ORDER BY mother_id").fetchall()
    return render_template("mothers.html", rows=rows)


@app.route("/mothers/new", methods=["GET", "POST"])
def mothers_new():
    db = get_db()
    if request.method == "POST":
        mother_id = request.form["mother_id"].strip()
        if not mother_id:
            flash("Mother ID is required.", "error")
            return redirect(url_for("mothers_new"))
        existing = db.execute(
            "SELECT 1 FROM mother_plants WHERE mother_id = ?", (mother_id,)
        ).fetchone()
        if existing:
            flash(f'Mother ID "{mother_id}" already exists.', "error")
            return redirect(url_for("mothers_new"))
        db.execute(
            """INSERT INTO mother_plants
               (mother_id, display_name, location, botanical_line1, botanical_line2, print_label, created_at)
               VALUES (?, ?, ?, ?, ?, 0, ?)""",
            (
                mother_id,
                request.form.get("display_name", "").strip(),
                request.form.get("location", "").strip(),
                request.form.get("botanical_line1", "").strip(),
                request.form.get("botanical_line2", "").strip(),
                datetime.utcnow().isoformat(),
            ),
        )
        db.commit()
        flash(f'Mother plant "{mother_id}" added.', "success")
        return redirect(url_for("mothers_list"))
    return render_template("mother_form.html", mother=None)


@app.route("/mothers/<mother_id>/edit", methods=["GET", "POST"])
def mothers_edit(mother_id):
    db = get_db()
    mother = db.execute(
        "SELECT * FROM mother_plants WHERE mother_id = ?", (mother_id,)
    ).fetchone()
    if not mother:
        abort(404)
    if request.method == "POST":
        db.execute(
            """UPDATE mother_plants SET display_name=?, location=?, botanical_line1=?, botanical_line2=?
               WHERE mother_id=?""",
            (
                request.form.get("display_name", "").strip(),
                request.form.get("location", "").strip(),
                request.form.get("botanical_line1", "").strip(),
                request.form.get("botanical_line2", "").strip(),
                mother_id,
            ),
        )
        db.commit()
        flash(f'Mother plant "{mother_id}" updated.', "success")
        return redirect(url_for("mothers_list"))
    return render_template("mother_form.html", mother=mother)


@app.route("/mothers/<mother_id>/flag_print", methods=["POST"])
def mothers_flag_print(mother_id):
    db = get_db()
    new_val = 1 if request.form.get("value") == "1" else 0
    db.execute("UPDATE mother_plants SET print_label=? WHERE mother_id=?", (new_val, mother_id))
    db.commit()
    return redirect(url_for("mothers_list"))


# ----------------------------------------------------------------
# Cuttings — "take cuttings from a mother" replaces the Google Form + onFormSubmit
# ----------------------------------------------------------------
@app.route("/cuttings")
def cuttings_list():
    db = get_db()
    rows = db.execute(
        """SELECT c.*, m.display_name AS mother_display_name
           FROM cuttings c JOIN mother_plants m ON m.mother_id = c.mother_id
           ORDER BY c.created_at DESC"""
    ).fetchall()
    return render_template("cuttings.html", rows=rows)


@app.route("/cuttings/new", methods=["GET", "POST"])
def cuttings_new():
    db = get_db()
    mothers = db.execute("SELECT * FROM mother_plants ORDER BY mother_id").fetchall()
    if request.method == "POST":
        mother_id = request.form["mother_id"]
        num_cuts = int(request.form.get("num_cuts", 0) or 0)
        date_taken = request.form.get("date_taken") or date.today().isoformat()

        mother = db.execute(
            "SELECT * FROM mother_plants WHERE mother_id = ?", (mother_id,)
        ).fetchone()
        if not mother:
            flash("Unknown mother plant.", "error")
            return redirect(url_for("cuttings_new"))
        if num_cuts < 1:
            flash("Number of cuttings must be at least 1.", "error")
            return redirect(url_for("cuttings_new"))

        seq = next_cutting_seq(db, mother_id)
        created = []
        for n in range(num_cuts):
            cid = make_cutting_id(mother_id, seq + n)
            db.execute(
                """INSERT INTO cuttings
                   (cutting_id, mother_id, full_display_name, label_line1, label_line2,
                    date_taken, sold, print_label, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?)""",
                (
                    cid,
                    mother_id,
                    mother["display_name"],
                    mother["botanical_line1"],
                    mother["botanical_line2"],
                    date_taken,
                    datetime.utcnow().isoformat(),
                ),
            )
            created.append(cid)
        db.commit()
        flash(f"Created {len(created)} cutting(s): {', '.join(created)}", "success")
        return redirect(url_for("cuttings_list"))
    return render_template("cutting_new.html", mothers=mothers)


@app.route("/cuttings/<cutting_id>/toggle", methods=["POST"])
def cuttings_toggle(cutting_id):
    db = get_db()
    field = request.form["field"]  # "sold" or "print_label"
    if field not in ("sold", "print_label"):
        abort(400)
    row = db.execute("SELECT * FROM cuttings WHERE cutting_id=?", (cutting_id,)).fetchone()
    if not row:
        abort(404)
    new_val = 0 if row[field] else 1
    db.execute(f"UPDATE cuttings SET {field}=? WHERE cutting_id=?", (new_val, cutting_id))
    db.commit()
    return redirect(url_for("cuttings_list"))


# ----------------------------------------------------------------
# Push sold cuttings -> outgoing log  (mirrors pushSoldToOutgoingLog)
# ----------------------------------------------------------------
@app.route("/push_sold", methods=["POST"])
def push_sold():
    db = get_db()
    sold_rows = db.execute("SELECT * FROM cuttings WHERE sold = 1").fetchall()
    today = date.today().isoformat()
    pushed = 0
    for r in sold_rows:
        existing = db.execute(
            "SELECT 1 FROM outgoing_log WHERE cutting_id=?", (r["cutting_id"],)
        ).fetchone()
        if not existing:
            db.execute(
                """INSERT INTO outgoing_log (date_out, cutting_id, full_display_name, qty, reason)
                   VALUES (?, ?, ?, 1, 'Sale')""",
                (today, r["cutting_id"], r["full_display_name"]),
            )
            pushed += 1
        db.execute("UPDATE cuttings SET sold=0 WHERE cutting_id=?", (r["cutting_id"],))
    db.commit()
    flash(f"Pushed {pushed} sold cutting(s) to Outgoing Log.", "success")
    return redirect(url_for("cuttings_list"))


@app.route("/outgoing")
def outgoing_list():
    db = get_db()
    rows = db.execute("SELECT * FROM outgoing_log ORDER BY id DESC").fetchall()
    return render_template("outgoing.html", rows=rows)


# ----------------------------------------------------------------
# Label exports — CSV (properly escaped) and PDF (real QR codes)
# ----------------------------------------------------------------
def build_csv(header, rows):
    buf = io.StringIO()
    writer = csv.writer(buf)  # csv module handles quoting/escaping correctly, no manual join(',')
    writer.writerow(header)
    for r in rows:
        writer.writerow(r)
    mem = io.BytesIO(buf.getvalue().encode("utf-8"))
    mem.seek(0)
    return mem


@app.route("/labels/mothers.csv")
def export_mothers_csv():
    db = get_db()
    rows = db.execute("SELECT * FROM mother_plants WHERE print_label = 1").fetchall()
    if not rows:
        flash("No mother plants flagged for print.", "error")
        return redirect(url_for("mothers_list"))
    out_rows = []
    for r in rows:
        qr_url = url_for("public_plant", mother_id=r["mother_id"], _external=True)
        out_rows.append([r["mother_id"], r["display_name"], r["botanical_line1"], r["botanical_line2"], qr_url])
    csv_file = build_csv(["Mother_ID", "Display_Name", "Label_Line1", "Label_Line2", "QR_Link"], out_rows)
    db.execute("UPDATE mother_plants SET print_label = 0 WHERE print_label = 1")
    db.commit()
    return send_file(csv_file, mimetype="text/csv", as_attachment=True, download_name="GM_Mother_Labels.csv")


@app.route("/labels/cuttings.csv")
def export_cuttings_csv():
    db = get_db()
    rows = db.execute("SELECT * FROM cuttings WHERE print_label = 1").fetchall()
    if not rows:
        flash("No cuttings flagged for print.", "error")
        return redirect(url_for("cuttings_list"))
    out_rows = []
    for r in rows:
        qr_url = url_for("public_cutting", cutting_id=r["cutting_id"], _external=True)
        out_rows.append(
            [r["cutting_id"], r["full_display_name"], r["label_line1"], r["label_line2"], r["date_taken"], qr_url]
        )
    csv_file = build_csv(
        ["Cutting_ID", "Full_Display_Name", "Label_Line1", "Label_Line2", "Date_Taken", "QR_Link"], out_rows
    )
    db.execute("UPDATE cuttings SET print_label = 0 WHERE print_label = 1")
    db.commit()
    return send_file(csv_file, mimetype="text/csv", as_attachment=True, download_name="GM_Cutting_Labels.csv")


def build_label_pdf(items):
    """items: list of dicts with id_text, line1, line2, qr_url. Renders a
    grid of Avery-5160-ish labels (3 cols) with a real per-item QR code."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    page_w, page_h = letter

    margin_x = 0.19 * inch
    margin_y = 0.5 * inch
    label_w = 2.6 * inch
    label_h = 1.0 * inch
    gap_x = 0.19 * inch
    cols = 3
    rows_per_page = int((page_h - 2 * margin_y) // label_h)

    col = 0
    row = 0
    for item in items:
        if row >= rows_per_page:
            c.showPage()
            row = 0
        x = margin_x + col * (label_w + gap_x)
        y = page_h - margin_y - (row + 1) * label_h

        c.rect(x, y, label_w, label_h)

        qr_buf = qr_png_bytes(item["qr_url"])
        qr_size = label_h - 0.15 * inch
        c.drawImage(
            ImageReader(qr_buf), x + 0.05 * inch, y + 0.075 * inch,
            width=qr_size, height=qr_size, preserveAspectRatio=True, mask="auto",
        )

        text_x = x + qr_size + 0.15 * inch
        c.setFont("Helvetica-Bold", 8)
        c.drawString(text_x, y + label_h - 0.25 * inch, item["id_text"][:26])
        c.setFont("Helvetica", 7)
        c.drawString(text_x, y + label_h - 0.45 * inch, (item["line1"] or "")[:28])
        c.drawString(text_x, y + label_h - 0.62 * inch, (item["line2"] or "")[:28])

        col += 1
        if col >= cols:
            col = 0
            row += 1

    c.save()
    buf.seek(0)
    return buf


@app.route("/labels/mothers.pdf")
def export_mothers_pdf():
    db = get_db()
    rows = db.execute("SELECT * FROM mother_plants WHERE print_label = 1").fetchall()
    if not rows:
        flash("No mother plants flagged for print.", "error")
        return redirect(url_for("mothers_list"))
    items = [
        {
            "id_text": r["mother_id"],
            "line1": r["botanical_line1"],
            "line2": r["botanical_line2"],
            "qr_url": url_for("public_plant", mother_id=r["mother_id"], _external=True),
        }
        for r in rows
    ]
    pdf = build_label_pdf(items)
    db.execute("UPDATE mother_plants SET print_label = 0 WHERE print_label = 1")
    db.commit()
    return send_file(pdf, mimetype="application/pdf", as_attachment=True, download_name="GM_Mother_Labels.pdf")


@app.route("/labels/cuttings.pdf")
def export_cuttings_pdf():
    db = get_db()
    rows = db.execute("SELECT * FROM cuttings WHERE print_label = 1").fetchall()
    if not rows:
        flash("No cuttings flagged for print.", "error")
        return redirect(url_for("cuttings_list"))
    items = [
        {
            "id_text": r["cutting_id"],
            "line1": r["label_line1"],
            "line2": r["label_line2"],
            "qr_url": url_for("public_cutting", cutting_id=r["cutting_id"], _external=True),
        }
        for r in rows
    ]
    pdf = build_label_pdf(items)
    db.execute("UPDATE cuttings SET print_label = 0 WHERE print_label = 1")
    db.commit()
    return send_file(pdf, mimetype="application/pdf", as_attachment=True, download_name="GM_Cutting_Labels.pdf")


# ----------------------------------------------------------------
# Public pages — what the QR codes actually link to.
# In the Sheets version, the QR just opened a prefilled Google Form.
# Here it opens a real info page, and the form to log new cuttings
# lives at /cuttings/new instead of a separate Google Form.
# ----------------------------------------------------------------
@app.route("/plant/<mother_id>")
def public_plant(mother_id):
    db = get_db()
    mother = db.execute("SELECT * FROM mother_plants WHERE mother_id=?", (mother_id,)).fetchone()
    if not mother:
        abort(404)
    cuttings = db.execute(
        "SELECT * FROM cuttings WHERE mother_id=? ORDER BY cutting_id", (mother_id,)
    ).fetchall()
    return render_template("public_plant.html", mother=mother, cuttings=cuttings)


@app.route("/plant/cutting/<cutting_id>")
def public_cutting(cutting_id):
    db = get_db()
    cutting = db.execute("SELECT * FROM cuttings WHERE cutting_id=?", (cutting_id,)).fetchone()
    if not cutting:
        abort(404)
    return render_template("public_cutting.html", cutting=cutting)


if __name__ == "__main__":
    init_db()
    app.run(debug=True, host="127.0.0.1", port=5000)
